In [1]:
import numpy as np 

In [4]:
# list convert into array

lst = [1,2,3,4,5]
print("This is my list :- ",lst)
print("Type of my list :- ",type(lst))
arr =np.array(lst)
print("This is my first array :- ",arr)
print("type of array :- ",type(arr))


This is my list :-  [1, 2, 3, 4, 5]
Type of my list :-  <class 'list'>
This is my first array :-  [1 2 3 4 5]
type of array :-  <class 'numpy.ndarray'>


In [6]:
arr =np.array([1,2,3,4,5,5])
print("This is my first array :- ",arr)
print("type of array :- ",type(arr))

This is my first array :-  [1 2 3 4 5 5]
type of array :-  <class 'numpy.ndarray'>


In [7]:
lst =list(range(1,25))

In [11]:
print(type(lst ))
arr =np.array(lst)
print(arr)
print(type(arr))

<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
<class 'numpy.ndarray'>


In [ ]:
arr =np.arange(2,22) #### 

In [14]:
print(arr)
print(type(arr))

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
<class 'numpy.ndarray'>


In [15]:
arr =np.zeros(10)

In [16]:
arr 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
arr =np.zeros((5,10))
arr 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr =np.ones(10)

In [20]:
print(arr )

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
arr =np.ones((5, 10)) ### 5 is row and 10 is coloum 

In [22]:
arr 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
arr=  np.linspace(1,10,5) ### 1 to 10 is range and total elements is 5 

In [28]:
arr 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr =np.arange(0,30)
### 1d array convert into 2d array 

In [30]:
arr =arr.reshape(5,6)

In [31]:
arr 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
arr =np.arange(0,30)
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
arr =np.random.randint(1,5,(5,2))

In [37]:
arr 

array([[3, 1],
       [4, 3],
       [2, 4],
       [2, 2],
       [3, 3]], dtype=int32)

In [38]:
arr =np.random.random(10)

In [39]:
arr 

array([0.79785204, 0.1619245 , 0.14704598, 0.47934168, 0.96486256,
       0.24538702, 0.09105346, 0.21343529, 0.27432735, 0.08616877])

In [40]:
arr =np.random.random((5,10))

In [41]:
arr 

array([[0.99519871, 0.39628383, 0.9189983 , 0.4431796 , 0.13677082,
        0.59081716, 0.51173354, 0.68175661, 0.38004447, 0.40347323],
       [0.19532569, 0.05841407, 0.58722511, 0.5069766 , 0.29221345,
        0.3232166 , 0.34905429, 0.64326707, 0.84685563, 0.05731398],
       [0.2451103 , 0.40215966, 0.29812588, 0.31374555, 0.16520166,
        0.29872849, 0.15147864, 0.09520014, 0.50663494, 0.14592365],
       [0.14027528, 0.52220406, 0.77635832, 0.81805786, 0.34387226,
        0.32336757, 0.49614468, 0.97251402, 0.1651264 , 0.54188821],
       [0.33555913, 0.0920121 , 0.89207519, 0.61810595, 0.61081683,
        0.15869354, 0.25968498, 0.31991007, 0.32535921, 0.67347428]])

### Array Attribute

In [42]:
arr =np.arange(60)

In [43]:
arr =arr.reshape(12,5)

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [45]:
print("shape of array :- ",arr.shape)
print("data type of array :- ", arr.dtype)
print("size of array :- ",arr.size)
print("number of dim :- ",arr.ndim)

shape of array :-  (12, 5)
data type of array :-  int64
size of array :-  60
number of dim :-  2


In [48]:
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [49]:
arr[1][0]

np.int64(5)

In [51]:
arr[-1][-1]

np.int64(59)

In [53]:
arr[11][-1]

np.int64(59)

In [54]:
arr[11][4]

np.int64(59)

In [55]:
arr[-1][-1]=100

In [56]:
arr 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [58]:
arr =arr.T

In [59]:
arr 

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55],
       [  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56],
       [  2,   7,  12,  17,  22,  27,  32,  37,  42,  47,  52,  57],
       [  3,   8,  13,  18,  23,  28,  33,  38,  43,  48,  53,  58],
       [  4,   9,  14,  19,  24,  29,  34,  39,  44,  49,  54, 100]])

In [60]:
#### 2d array convert into 2d array 

In [63]:
arr=arr.flatten() 

In [64]:
print("shape of array :- ",arr.shape)
print("data type of array :- ", arr.dtype)
print("size of array :- ",arr.size)
print("number of dim :- ",arr.ndim)

shape of array :-  (60,)
data type of array :-  int64
size of array :-  60
number of dim :-  1


In [65]:
arr =np.arange(60).reshape(12,5)

In [67]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

### 3D array 

In [70]:
arr =np.arange(225).reshape(5,15,3)### 5 is table ir 15 row and 3 coloums 

In [71]:
arr 

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [72]:
print("shape of array :- ",arr.shape)
print("data type of array :- ", arr.dtype)
print("size of array :- ",arr.size)
print("number of dim :- ",arr.ndim)

shape of array :-  (5, 15, 3)
data type of array :-  int64
size of array :-  225
number of dim :-  3


In [74]:
arr[0][0]

array([0, 1, 2])

In [75]:
arr[1]

array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [76]:
arr[4]

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [77]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
print(arr+2)
print(arr*2)
print(arr1/arr2)
print(arr1*arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1**2)
print(arr1**3)